name: takehometest
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  http: ^1.2.0
  riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  flutter_riverpod: ^2.4.9
  cached_network_image: ^3.3.1
  intl: ^0.17.0
  webview_flutter: ^4.5.0
  mocktail: ^1.0.3
  icons_launcher: ^2.1.7
  flutter_native_splash: ^2.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6

  riverpod_generator: ^2.3.5

  riverpod_lint: ^2.3.3
  flutter_lints: ^2.0.0


icons_launcher:
  image_path: "assets/icon.png"
  adaptive_background_color: '#F7F7F7'
  platforms:
    android:
      enable: true
    ios:
      enable: true



flutter_native_splash:

  color: "#F7F7F7"
 
  image: "assets/icon.png"


  android_12:
    
    image: "assets/icon.png"


    color: "#F7F7F7"

   
flutter:


  uses-material-design: true


  assets:
    - assets/


  